stages:
  - compile

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: normal
  ARTIFACTS_NAME: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  ARTIFACTS_PATH: bin.tar

.compile-job: &compile-job
  stage: compile
  artifacts:
    when: on_success
    name: $ARTIFACTS_NAME
    expire_in: 1h
    paths:
      - bin.tar
  script:
    - echo -e "Script Arguments:\t $CONFIG_ARGS"

compile:cpp:
  <<: *compile-job
  image: acai-oneapi
  tags:
    - acai-cpu

